import React, { useState } from 'react';
import { 
  X, 
  Share2, 
  Copy, 
  Check, 
  Mail, 
  Sparkles, 
  Flame, 
  CheckCircle2, 
  Send, 
  ExternalLink,
  MessageSquare,
  Smartphone,
  FileText,
  Calendar,
  Award
} from 'lucide-react';
import { Habit, UserProfile, DayWorkUpdateEntry } from '../../types';

interface WorkShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  userProfile?: UserProfile;
  completedCount: number;
  totalCount: number;
  currentStreak: number;
  habits: Habit[];
  workHistory?: DayWorkUpdateEntry[];
  initialPlatform?: 'whatsapp' | 'instagram' | 'email' | 'all';
}

export const WorkShareModal: React.FC<WorkShareModalProps> = ({
  isOpen,
  onClose,
  userProfile,
  completedCount,
  totalCount,
  currentStreak,
  habits,
  workHistory = [],
  initialPlatform = 'all',
}) => {
  const [copied, setCopied] = useState(false);
  const [reportFormat, setReportFormat] = useState<'summary' | 'detailed' | 'instagram'>('summary');
  const [activeTab, setActiveTab] = useState<'quick' | 'channels' | 'preview'>('channels');

  if (!isOpen) return null;

  const userName = userProfile?.name || 'Alex';
  const completionPercentage = Math.round((completedCount / (totalCount || 1)) * 100);
  const todayDateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });

  const completedHabitsList = habits.filter(h => h.completedToday);
  const latestWorkLog = workHistory[0]?.workLogText || habits.find(h => h.dailyWorkLog)?.dailyWorkLog;

  // Generate share message variants
  const getSummaryText = () => {
    let text = `🚀 *Daily Work & Habit Update — ${userName}*\n`;
    text += `📅 ${todayDateStr}\n\n`;
    text += `✅ *Progress:* ${completedCount}/${totalCount} Habits Completed (${completionPercentage}%)\n`;
    text += `🔥 *Streak:* ${currentStreak} Consecutive Days\n`;
    
    if (completedHabitsList.length > 0) {
      text += `\n🎯 *Today's Completed Rituals:*\n`;
      completedHabitsList.slice(0, 5).forEach((h) => {
        const timeCheck = h.completedTime ? ` (at ${h.completedTime})` : '';
        text += `• ${h.name}${timeCheck}\n`;
      });
      if (completedHabitsList.length > 5) {
        text += `• +${completedHabitsList.length - 5} more habits!\n`;
      }
    }

    if (latestWorkLog) {
      text += `\n📝 *Work Note:* "${latestWorkLog}"\n`;
    }

    text += `\n✨ Consistency is key! Tracked with Daily Rituals & Work Tracker.`;
    return text;
  };

  const getDetailedReportText = () => {
    let text = `📋 *EXECUTIVE DAILY WORK & HABIT REPORT*\n`;
    text += `User: ${userName} | Date: ${todayDateStr}\n`;
    text += `------------------------------------\n`;
    text += `📊 METRICS SUMMARY:\n`;
    text += `• Completion Rate: ${completionPercentage}%\n`;
    text += `• Habits Done: ${completedCount} of ${totalCount}\n`;
    text += `• Active Streak: ${currentStreak} days\n\n`;

    text += `📌 COMPLETED HABITS & CHECK-IN TIMES:\n`;
    if (completedHabitsList.length === 0) {
      text += `• No habits marked complete yet today.\n`;
    } else {
      completedHabitsList.forEach((h, idx) => {
        text += `${idx + 1}. ${h.name} [${h.category}] — ${h.completedTime || 'Completed'}\n`;
        if (h.dailyWorkLog) {
          text += `   ↳ Note: ${h.dailyWorkLog}\n`;
        }
      });
    }

    if (workHistory.length > 0) {
      text += `\n🕒 RECENT WORK LOG ENTRIES:\n`;
      workHistory.slice(0, 3).forEach((item) => {
        text += `• [${item.completedTime}] ${item.habitName}: "${item.workLogText}" (Rating: ${'★'.repeat(item.rating)})\n`;
      });
    }

    text += `\nGenerated by Ritual & Work Hub. Keep crushing your goals!`;
    return text;
  };

  const getInstagramCaptionText = () => {
    let text = `⚡ Another day in the books! Today's work & habit progress: ${completionPercentage}% complete! 🚀\n\n`;
    text += `🔥 ${currentStreak}-Day Consistency Streak\n`;
    text += `✅ ${completedCount}/${totalCount} daily rituals knocked out\n\n`;
    if (latestWorkLog) {
      text += `💭 Focus for today: "${latestWorkLog}"\n\n`;
    }
    text += `Showing up every single day and putting in the work. How did you do today?\n\n`;
    text += `#DailyHabits #Productivity #Discipline #HabitMastery #WorkProgress #Streak #GoalGetter #SelfImprovement`;
    return text;
  };

  const currentMessage = reportFormat === 'summary' 
    ? getSummaryText() 
    : reportFormat === 'detailed' 
      ? getDetailedReportText() 
      : getInstagramCaptionText();

  const handleCopyText = (textToCopy = currentMessage) => {
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  // Channel share handlers
  const handleShareWhatsApp = () => {
    const text = encodeURIComponent(currentMessage);
    const url = `https://api.whatsapp.com/send?text=${text}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const handleShareInstagram = () => {
    // Copy the optimized caption to clipboard first
    const caption = getInstagramCaptionText();
    navigator.clipboard.writeText(caption);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
    // Direct link to open Instagram in new tab / app
    window.open('https://www.instagram.com/', '_blank', 'noopener,noreferrer');
  };

  const handleShareEmail = () => {
    const subject = encodeURIComponent(`Daily Work & Habit Summary — ${userName} (${todayDateStr})`);
    const body = encodeURIComponent(reportFormat === 'summary' ? getSummaryText() : getDetailedReportText());
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
  };

  const handleShareTwitter = () => {
    const tweet = `Crushed ${completionPercentage}% of my daily work & habits today with a ${currentStreak}-day streak! 🔥 Every day counts. #Productivity #DailyHabits`;
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweet)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const handleShareTelegram = () => {
    const text = encodeURIComponent(currentMessage);
    const url = `https://t.me/share/url?url=${encodeURIComponent(window.location.origin)}&text=${text}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const handleShareLinkedIn = () => {
    const text = encodeURIComponent(currentMessage);
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.href)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const handleNativeShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Daily Work & Habit Progress — ${userName}`,
          text: currentMessage,
          url: window.location.href,
        });
      } catch (err) {
        console.log('User cancelled or share error', err);
      }
    } else {
      handleCopyText();
    }
  };

  const hasNativeShare = typeof navigator !== 'undefined' && !!navigator.share;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
      <div 
        className="relative w-full max-w-2xl bg-white dark:bg-gray-900 rounded-3xl shadow-2xl border border-gray-200 dark:border-gray-800 overflow-hidden flex flex-col max-h-[90vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="relative p-6 bg-gradient-to-r from-emerald-600 via-teal-600 to-cyan-600 text-white">
          <button
            onClick={onClose}
            className="absolute top-5 right-5 p-2 rounded-full bg-white/20 hover:bg-white/30 text-white transition-colors cursor-pointer"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>

          <div className="flex items-center space-x-2 text-emerald-100 text-xs font-bold uppercase tracking-wider mb-1">
            <Share2 className="w-4 h-4" />
            <span>Work & Habit Share Center</span>
          </div>
          <h2 className="text-2xl font-black tracking-tight">
            Share Your Work Progress
          </h2>
          <p className="text-emerald-50 text-xs sm:text-sm mt-1 max-w-md">
            Broadcast today’s completed habits, streaks, and site work notes via WhatsApp, Instagram, Email, or more!
          </p>

          {/* Quick Metrics Bar */}
          <div className="mt-4 flex flex-wrap items-center gap-2 pt-3 border-t border-white/20 text-xs font-semibold">
            <span className="px-2.5 py-1 rounded-full bg-white/20 text-white flex items-center space-x-1">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-200" />
              <span>{completedCount}/{totalCount} Completed ({completionPercentage}%)</span>
            </span>
            <span className="px-2.5 py-1 rounded-full bg-amber-400/30 text-amber-100 flex items-center space-x-1">
              <Flame className="w-3.5 h-3.5 fill-amber-300" />
              <span>{currentStreak} Day Streak</span>
            </span>
            <span className="px-2.5 py-1 rounded-full bg-cyan-400/30 text-cyan-100 flex items-center space-x-1">
              <Calendar className="w-3.5 h-3.5" />
              <span>{todayDateStr}</span>
            </span>
          </div>
        </div>

        {/* Format Selector Pills */}
        <div className="px-6 pt-4 pb-2 bg-slate-50 dark:bg-gray-800/50 border-b border-gray-200 dark:border-gray-800 flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center space-x-1 text-xs font-semibold text-gray-500 dark:text-gray-400">
            <span>Report Format:</span>
          </div>
          <div className="flex items-center space-x-1.5 p-1 bg-gray-200/80 dark:bg-gray-700/60 rounded-xl text-xs font-bold">
            <button
              onClick={() => setReportFormat('summary')}
              className={`px-3 py-1 rounded-lg transition-all cursor-pointer ${
                reportFormat === 'summary'
                  ? 'bg-white dark:bg-gray-900 text-emerald-600 dark:text-emerald-400 shadow-xs'
                  : 'text-gray-600 dark:text-gray-300 hover:text-gray-900'
              }`}
            >
              💬 Social Summary
            </button>
            <button
              onClick={() => setReportFormat('detailed')}
              className={`px-3 py-1 rounded-lg transition-all cursor-pointer ${
                reportFormat === 'detailed'
                  ? 'bg-white dark:bg-gray-900 text-emerald-600 dark:text-emerald-400 shadow-xs'
                  : 'text-gray-600 dark:text-gray-300 hover:text-gray-900'
              }`}
            >
              📄 Executive Report
            </button>
            <button
              onClick={() => setReportFormat('instagram')}
              className={`px-3 py-1 rounded-lg transition-all cursor-pointer ${
                reportFormat === 'instagram'
                  ? 'bg-white dark:bg-gray-900 text-pink-600 dark:text-pink-400 shadow-xs'
                  : 'text-gray-600 dark:text-gray-300 hover:text-gray-900'
              }`}
            >
              📸 Instagram Story/Post
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1">

          {/* 1. Primary Channels Grid */}
          <div>
            <h3 className="text-xs font-black uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-3">
              Direct Share Channels
            </h3>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
              
              {/* WhatsApp Button */}
              <button
                type="button"
                onClick={handleShareWhatsApp}
                className="group p-3.5 rounded-2xl bg-emerald-500 hover:bg-emerald-600 text-white flex flex-col items-center justify-center text-center shadow-md shadow-emerald-500/20 hover:scale-[1.02] transition-all cursor-pointer"
              >
                <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                  {/* WhatsApp SVG Icon */}
                  <svg className="w-5 h-5 fill-current" viewBox="0 0 24 24">
                    <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981zm11.387-5.464c-.074-.124-.272-.198-.57-.347-.297-.149-1.758-.868-2.031-.967-.272-.099-.47-.149-.669.149-.198.297-.768.967-.941 1.165-.173.198-.347.223-.644.074-.297-.149-1.255-.462-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.297-.347.446-.521.151-.172.2-.296.3-.495.099-.198.05-.372-.025-.521-.075-.148-.669-1.611-.916-2.206-.242-.579-.487-.501-.669-.51l-.57-.01c-.198 0-.52.074-.792.372s-1.04 1.016-1.04 2.479 1.065 2.876 1.213 3.074c.149.198 2.095 3.2 5.076 4.487.709.306 1.263.489 1.694.626.712.226 1.36.194 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.695.248-1.29.173-1.414z"/>
                  </svg>
                </div>
                <span className="text-sm font-extrabold">WhatsApp</span>
                <span className="text-[10px] text-emerald-100 font-medium mt-0.5">Direct chat or status</span>
              </button>

              {/* Instagram Button */}
              <button
                type="button"
                onClick={handleShareInstagram}
                className="group p-3.5 rounded-2xl bg-gradient-to-tr from-amber-500 via-rose-500 to-purple-600 hover:opacity-95 text-white flex flex-col items-center justify-center text-center shadow-md shadow-rose-500/20 hover:scale-[1.02] transition-all cursor-pointer"
              >
                <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                  {/* Instagram SVG Icon */}
                  <svg className="w-5 h-5 fill-current" viewBox="0 0 24 24">
                    <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
                  </svg>
                </div>
                <span className="text-sm font-extrabold">Instagram</span>
                <span className="text-[10px] text-pink-100 font-medium mt-0.5">Story copy & open app</span>
              </button>

              {/* Mail Button */}
              <button
                type="button"
                onClick={handleShareEmail}
                className="group p-3.5 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white flex flex-col items-center justify-center text-center shadow-md shadow-blue-500/20 hover:scale-[1.02] transition-all cursor-pointer"
              >
                <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                  <Mail className="w-5 h-5" />
                </div>
                <span className="text-sm font-extrabold">Email / Mail</span>
                <span className="text-[10px] text-blue-100 font-medium mt-0.5">Send work report</span>
              </button>

              {/* Twitter / X Button */}
              <button
                type="button"
                onClick={handleShareTwitter}
                className="group p-3.5 rounded-2xl bg-gray-900 hover:bg-black text-white flex flex-col items-center justify-center text-center shadow-md hover:scale-[1.02] transition-all cursor-pointer"
              >
                <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                  {/* X (Twitter) Logo */}
                  <svg className="w-4 h-4 fill-current" viewBox="0 0 24 24">
                    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
                  </svg>
                </div>
                <span className="text-sm font-extrabold">X / Twitter</span>
                <span className="text-[10px] text-gray-300 font-medium mt-0.5">Post daily win</span>
              </button>

              {/* Telegram Button */}
              <button
                type="button"
                onClick={handleShareTelegram}
                className="group p-3.5 rounded-2xl bg-sky-500 hover:bg-sky-600 text-white flex flex-col items-center justify-center text-center shadow-md shadow-sky-500/20 hover:scale-[1.02] transition-all cursor-pointer"
              >
                <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                  <Send className="w-5 h-5" />
                </div>
                <span className="text-sm font-extrabold">Telegram</span>
                <span className="text-[10px] text-sky-100 font-medium mt-0.5">Send to team or saved</span>
              </button>

              {/* Native Mobile Share / Device Sheet */}
              <button
                type="button"
                onClick={handleNativeShare}
                className="group p-3.5 rounded-2xl bg-indigo-600 hover:bg-indigo-700 text-white flex flex-col items-center justify-center text-center shadow-md shadow-indigo-500/20 hover:scale-[1.02] transition-all cursor-pointer"
              >
                <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                  <Smartphone className="w-5 h-5" />
                </div>
                <span className="text-sm font-extrabold">More Apps...</span>
                <span className="text-[10px] text-indigo-100 font-medium mt-0.5">System share sheet</span>
              </button>

            </div>
          </div>

          {/* 2. Visual Story Card Preview (Great for Instagram Screenshots or Team Updates) */}
          <div className="p-5 rounded-2xl bg-gradient-to-br from-slate-900 via-gray-900 to-emerald-950 text-white border border-emerald-500/30 shadow-lg relative overflow-hidden">
            <div className="absolute top-0 right-0 w-48 h-48 bg-emerald-500/10 rounded-full blur-2xl pointer-events-none" />
            
            <div className="relative z-10 flex items-center justify-between border-b border-white/10 pb-3 mb-3">
              <div className="flex items-center space-x-2">
                <Sparkles className="w-4 h-4 text-emerald-400" />
                <span className="text-xs font-bold uppercase tracking-wider text-emerald-300">
                  {userName}'s Daily Victory Card
                </span>
              </div>
              <span className="text-[11px] font-mono text-gray-400">{todayDateStr}</span>
            </div>

            <div className="relative z-10 grid grid-cols-3 gap-2 py-2 text-center">
              <div className="p-2.5 rounded-xl bg-white/5 border border-white/10">
                <span className="block text-2xl font-black text-emerald-400 font-mono">
                  {completionPercentage}%
                </span>
                <span className="text-[10px] text-gray-300 uppercase font-semibold">Done Today</span>
              </div>
              <div className="p-2.5 rounded-xl bg-white/5 border border-white/10">
                <span className="block text-2xl font-black text-amber-400 font-mono">
                  {currentStreak}
                </span>
                <span className="text-[10px] text-gray-300 uppercase font-semibold">Day Streak 🔥</span>
              </div>
              <div className="p-2.5 rounded-xl bg-white/5 border border-white/10">
                <span className="block text-2xl font-black text-cyan-400 font-mono">
                  {completedCount}/{totalCount}
                </span>
                <span className="text-[10px] text-gray-300 uppercase font-semibold">Habits Crushed</span>
              </div>
            </div>

            {latestWorkLog && (
              <div className="mt-3 p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-xs text-emerald-200 italic">
                "{latestWorkLog}"
              </div>
            )}
          </div>

          {/* 3. Text Message Preview & 1-Click Copy */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-black uppercase tracking-wider text-gray-500 dark:text-gray-400">
                Formatted Text Preview ({reportFormat})
              </label>
              
              <button
                type="button"
                onClick={() => handleCopyText()}
                className={`inline-flex items-center space-x-1.5 px-3 py-1 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                  copied 
                    ? 'bg-emerald-600 text-white shadow-xs' 
                    : 'bg-emerald-50 dark:bg-emerald-950/80 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-100'
                }`}
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied to Clipboard!' : 'Copy Formatted Text'}</span>
              </button>
            </div>

            <div className="relative">
              <pre className="w-full p-4 rounded-2xl bg-gray-50 dark:bg-gray-950 border border-gray-200 dark:border-gray-800 text-xs text-gray-800 dark:text-gray-200 font-mono whitespace-pre-wrap leading-relaxed max-h-48 overflow-y-auto">
                {currentMessage}
              </pre>
            </div>
          </div>

        </div>

        {/* Modal Footer */}
        <div className="p-4 px-6 bg-gray-50 dark:bg-gray-800/80 border-t border-gray-200 dark:border-gray-800 flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center space-x-2 text-xs text-gray-500 dark:text-gray-400">
            <Sparkles className="w-3.5 h-3.5 text-emerald-500" />
            <span>Works instantly on mobile and desktop</span>
          </div>

          <div className="flex items-center space-x-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl border border-gray-300 dark:border-gray-700 hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300 text-xs font-bold transition-colors cursor-pointer"
            >
              Done
            </button>
            <button
              type="button"
              onClick={() => handleCopyText()}
              className="px-5 py-2 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white text-xs font-bold shadow-md shadow-emerald-500/20 flex items-center space-x-1.5 transition-all cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Share2 className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy & Share'}</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
